# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ExampleModel')),
            ],
        ),
    ]
