# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_linkexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='linkexample',
            name='firstname',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='LinkExample',
        ),
    ]
