# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_gamemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='player',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='username',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
