# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170807_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
