# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_gamemodel_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=50)),
            ],
        ),
    ]
